BEGIN;

CREATE TABLE IF NOT EXISTS inventory.reusable_item_units (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    unit_code varchar(50) NOT NULL,
    item_id uuid NOT NULL,
    receive_item_id integer NULL,
    serial_no varchar(100) NULL,
    department_id integer NULL,
    status varchar(20) NOT NULL DEFAULT 'AVAILABLE',
    condition varchar(20) NOT NULL DEFAULT 'GOOD',
    note text NULL,
    created_at timestamptz NULL DEFAULT now(),
    updated_at timestamptz NULL DEFAULT now(),
    deleted_at timestamptz NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'reusable_item_units_unit_code_key'
    ) THEN
        ALTER TABLE inventory.reusable_item_units
            ADD CONSTRAINT reusable_item_units_unit_code_key UNIQUE (unit_code);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_reusable_unit_item'
    ) THEN
        ALTER TABLE inventory.reusable_item_units
            ADD CONSTRAINT fk_reusable_unit_item
            FOREIGN KEY (item_id)
            REFERENCES inventory.items (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_reusable_unit_receive_item'
    ) THEN
        ALTER TABLE inventory.reusable_item_units
            ADD CONSTRAINT fk_reusable_unit_receive_item
            FOREIGN KEY (receive_item_id)
            REFERENCES inventory.receive_item (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_reusable_unit_department'
    ) THEN
        ALTER TABLE inventory.reusable_item_units
            ADD CONSTRAINT fk_reusable_unit_department
            FOREIGN KEY (department_id)
            REFERENCES public.departments (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_reusable_units_dept_id
    ON inventory.reusable_item_units (department_id);

CREATE INDEX IF NOT EXISTS idx_reusable_units_item_id
    ON inventory.reusable_item_units (item_id);

CREATE INDEX IF NOT EXISTS idx_reusable_units_status
    ON inventory.reusable_item_units (status);

CREATE TABLE IF NOT EXISTS inventory.reusable_item_unit_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id uuid NOT NULL,
    action varchar(30) NOT NULL,
    from_department_id integer NULL,
    to_department_id integer NULL,
    ref_doc_no varchar(50) NULL,
    note text NULL,
    performed_by uuid NULL,
    created_at timestamptz NULL DEFAULT now()
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_reusable_unit_log_unit'
    ) THEN
        ALTER TABLE inventory.reusable_item_unit_logs
            ADD CONSTRAINT fk_reusable_unit_log_unit
            FOREIGN KEY (unit_id)
            REFERENCES inventory.reusable_item_units (id)
            ON DELETE CASCADE
            ON UPDATE NO ACTION;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_reusable_unit_logs_action
    ON inventory.reusable_item_unit_logs (action);

CREATE INDEX IF NOT EXISTS idx_reusable_unit_logs_created_at
    ON inventory.reusable_item_unit_logs (created_at);

CREATE INDEX IF NOT EXISTS idx_reusable_unit_logs_unit_id
    ON inventory.reusable_item_unit_logs (unit_id);

COMMIT;
