const express = require('express')
const router = express.Router()

const { mw } = require('../middleware/auth')
const healthController = require('../controllers/health.controller')
const itemRoutes = require('./item.routes')
const lotRoutes = require('./lot.routes')
const requisitionRoutes = require('./requisition.routes')
const categoryRoutes = require('./category.route')
const warehouseRoutes = require('./warehouse.route')
const unitRoutes = require('./unit.route')
const supplierRoutes = require('./supplier.route')
const receiveRoutes = require('./receive.routes')
const fileRoutes = require('./file.routes')
const assetRoutes = require('./asset.route')
const departmentRoutes = require('./user.route')
const stockMovementRoutes = require('./stockmovement.routes')
const borrowRoutes = require('./borrow.routes')
const reusableItemRoutes = require('./reusableItem.routes')
const notificationRoutes = require('./notification.routes')
const barcodeRoutes = require('./barcode.routes')
const settingsRoutes = require('./settings.routes')
const analyticsRoutes = require('./analytics.routes')
const reportsRoutes = require('./reports.routes')
const profileRoutes = require('./profile.routes')
const lookupRoutes  = require('./lookup.routes')

router.get('/health', healthController.check)

const v1 = express.Router()
v1.use(mw)           // every /v1/* route requires a valid Supabase JWT
router.use('/v1', v1)

v1.use('/items', itemRoutes)
v1.use('/lots', lotRoutes)
v1.use('/requisitions', requisitionRoutes)
v1.use('/borrows', borrowRoutes)
v1.use('/categories', categoryRoutes)
v1.use('/warehouses', warehouseRoutes)
v1.use('/units', unitRoutes)
v1.use('/suppliers', supplierRoutes)
v1.use('/receives', receiveRoutes)
v1.use('/files', fileRoutes)
v1.use('/assets', assetRoutes)
v1.use('/reusable-items', reusableItemRoutes)
v1.use('/departments', departmentRoutes)
v1.use('/stock-movements', stockMovementRoutes)
v1.use('/notifications', notificationRoutes)
v1.use('/barcodes', barcodeRoutes)
v1.use('/settings', settingsRoutes)
v1.use('/analytics', analyticsRoutes)
v1.use('/reports', reportsRoutes)
v1.use('/user/profile', profileRoutes)
v1.use('/lookup',       lookupRoutes)

module.exports = router
