const LOT_STATUS = {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    CANCELLED: 'CANCELLED'
};

const LOT_EXPIRY_STATUS = {
    NORMAL: 'NORMAL',
    NEAR_EXPIRY: 'NEAR_EXPIRY',
    EXPIRED: 'EXPIRED'
};

const STOCK_MOVEMENT_TYPES = {
    ADJUST_OUT: 'ADJUST_OUT',
    UPDATE: 'UPDATE'
};

module.exports = {
    LOT_STATUS,
    LOT_EXPIRY_STATUS,
    STOCK_MOVEMENT_TYPES
};
